apiVersion: v1
kind: Pod
metadata:
        name: test1
spec:
        containers:
                - name: c1
                  image: xbfu1994/test:v1
                  command: ['python']
                  args: ['/workspace/pytorch-tutorial/tutorials/02-intermediate/convolutional_neural_network/main.py']
                  resources:
                          limits:
                                  nvidia.com/gpu: 1
